# .travis.yml 

# for auto testing

language: python
python:
  - "3.6"
# dependencies installation
install:
  - pip install -r requirements.txt
# add environment variable
before_script:
  - export APP_SETTINGS="development"
  - psql -c 'CREATE DATABASE thriller;' -U postgres
# start test
script:
  - py.test --cov=app
# send info to coveralls
after_success:
   coveralls
