# .travis.yml 

# for auto testing

language: python
python:
  - "3.6"
# dependencies installation
install:
  - pip install -r requirements.txt
# add environment variable
before_script:
  - export APP_SETTINGS="development"
  - psql -c 'CREATE DATABASE thriller;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d thriller
  - psql -c 'CREATE TABLE users (
  ID serial PRIMARY KEY,
  username VARCHAR (255) NOT NULL,
  email VARCHAR (255) NOT NULL,
  password VARCHAR (255)
  );' -U postgres -d thriller

  - psql -c 'CREATE TABLE entries (
  ID serial PRIMARY KEY,
  title VARCHAR (255) NOT NULL,
  date_created VARCHAR (255) NOT NULL,
  description VARCHAR (255) NOT NULL,
  owner_id integer NOT NULL,
  CONSTRAINT users_id_fkey FOREIGN KEY (id)
      REFERENCES users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
  );' -U postgres -d thriller
# start test
script:
  - py.test --cov=app
# send info to coveralls
after_success:
   coveralls
